/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Agent {
  /**
   * The identifier for the Agent object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Agent
   */
  "@type": "ods:Agent";
  /**
   * Indicates the role of the agent
   */
  "ods:agentRole": string;
  /**
   * Indicates the type of agent
   */
  "ods:agentType": string;
  /**
   * Primary identifier of the agent, additional identifiers can go in the identifiers array
   */
  "ods:agentID"?: string;
  /**
   * Full name of the agent
   */
  "ods:agentName": string;
  /**
   * Date the agent began the role
   */
  "ods:agentRoleBegan"?: string;
  /**
   * Date the agent ended the role
   */
  "ods:agentRoleEnded"?: string;
  /**
   * Order of the agent in the role. Can be used to indicate the order of importance
   */
  "ods:agentRoleOrder"?: number;
  /**
   * Contains zero or more ods:Identifier objects
   */
  "ods:hasIdentifier"?: Identifier[];
}
/**
 * Based on https://rs.gbif.org/extension/gbif/1.0/identifier.xml but includes ods specific terms
 */
export interface Identifier {
  /**
   * The identifier for the Identifier object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Identifier
   */
  "@type": "ods:Identifier";
  /**
   * The type of the identifier, https://purl.org/dc/elements/1.1/title
   */
  "dcterms:title": string;
  /**
   * The local title of the identifier
   */
  "ods:localTitle"?: string;
  /**
   * The value for the identifier, https://purl.org/dc/terms/identifier
   */
  "dcterms:identifier": string;
  /**
   * Mime type of content returned by identifier in case the identifier is resolvable. https://purl.org/dc/terms/format
   */
  "dcterms:format"?: string;
  /**
   * Keywords qualifying the identifier https://purl.org/dc/terms/subject
   */
  "dcterms:subject"?: string;
  /**
   * Indicates whether the identifier is part of the physical label
   */
  "ods:isPartOfLabel"?: boolean;
  /**
   * Indicates whether the identifier is part of the barcode or nfc chip
   */
  "ods:isBarcodeOrNFC"?: boolean;
  /**
   * Indicates whether the identifier is a persistent identifier
   */
  "ods:isIDPersistent"?: boolean;
}
