/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Target of an annotation
 */
export interface AnnotationTarget {
  /**
   * This is the PID of the target object. Valid targets are the Digital Specimen, Digital Media Object or another annotation.
   */
  "@id": string;
  /**
   * The type of the target object
   */
  "@type": string;
  /**
   * This is the PID of the target object. Valid targets are the Digital Specimen, Digital Media Object or another Annotation.
   */
  "dcterms:identifier": string;
  /**
   * This is the handle to the type of the target object.
   */
  "ods:fdoType": string;
  /**
   * Optional field to indicate the part of the target object that is being annotated. It can be a field, a class or a region of interest.
   */
  "oa:hasSelector"?:
    | {
        /**
         * A selector for an individual term
         */
        "@type": "ods:TermSelector";
        /**
         * The full jsonPath in block notation of the field being annotated. Following: https://goessner.net/articles/JsonPath/index.html#e2
         */
        "ods:term": string;
      }
    | {
        /**
         * A selector for an individual class
         */
        "@type": "ods:ClassSelector";
        /**
         * The full jsonPath in block notation of the class being annotated. Following: https://goessner.net/articles/JsonPath/index.html#e2
         */
        "ods:class": string;
      }
    | {
        /**
         * A selector for an specific Region of Interest (Roi). Only applicable on media objects.
         */
        "@type": "oa:FragmentSelector";
        /**
         * A region of interest located within the subject media item
         */
        "ac:hasROI": {
          /**
           * The horizontal position of a reference point, measured from the left side of the media item and expressed as a decimal fraction of the width of the media item
           */
          "ac:xFrac": number;
          /**
           * The vertical position of a reference point, measured from the top of the media item and expressed as a decimal fraction of the height of the media item
           */
          "ac:yFrac": number;
          /**
           * The width of the bounding rectangle, expressed as a decimal fraction of the width of the media item
           */
          "ac:widthFrac": number;
          /**
           * The height of the bounding rectangle, expressed as a decimal fraction of the height of the media item
           */
          "ac:heightFrac": number;
        };
        /**
         * Indicates the vocabulary that the ROI conforms to
         */
        "dcterms:conformsTo": "https://ac.tdwg.org/termlist/#711-region-of-interest-vocabulary";
      };
}
