/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Body of an annotation
 */
export interface AnnotationBody {
  /**
   * https://www.w3.org/TR/annotation-vocab/#textualbody
   */
  "@type": string;
  /**
   * An array of multiple values in string representation specific for the particular selector
   */
  "oa:value": string[];
  /**
   * Indicates how the value came to be. https://purl.org/dc/terms/references
   */
  "dcterms:references"?: string;
  /**
   * A score between 0 and 1 indicating the confidence in the value. 1 is the highest confidence and 0 is the lowest.
   */
  "ods:score"?: number;
}
