/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Annotation {
  "ods:id": string;
  "rdf:type": "Annotation";
  "ods:version": number;
  "oa:motivation": "ods:adding" | "oa:assessing" | "oa:editing" | "oa:commenting";
  "oa:motivatedBy"?: string;
  "oa:target": {
    "ods:id": string;
    "ods:type": string;
    "oa:selector"?:
      | {
          "ods:type": "FieldValueSelector";
          "ods:field": string;
          [k: string]: unknown;
        }
      | {
          "ods:type": "ClassValueSelector";
          "oa:class": string;
          [k: string]: unknown;
        }
      | {
          "ods:type"?: "FragmentSelector";
          "ac:hasRoi"?: {
            "ac:xFrac": number;
            "ac:yFrac": number;
            "ac:widthFrac": number;
            "ac:heightFrac": number;
            [k: string]: unknown;
          };
          "dcterms:conformsTo"?: string;
          [k: string]: unknown;
        };
    [k: string]: unknown;
  };
  "oa:body": {
    "ods:type": string;
    "oa:value": unknown[];
    "dcterms:reference"?: string;
    "ods:score"?: number;
    [k: string]: unknown;
  };
  "oa:creator": {
    "ods:type": string;
    "foaf:name"?: string;
    "ods:id": string;
    [k: string]: unknown;
  };
  "dcterms:created": string;
  "ods:deletedOn"?: string;
  "oa:generated"?: string;
  "as:generator": {
    "ods:id": string;
    "foaf:name"?: string;
    "ods:type": string;
    [k: string]: unknown;
  };
  "schema.org:aggregateRating"?: {
    "ods:type": string;
    "schema.org:ratingCount": number;
    "schema.org:ratingValue": number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
