/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Body of an annotation, contains the annotation as an array of text values in `oa:value`
 */
export interface AnnotationBody {
  /**
   * The type of the object, in this case oa:TextualBody
   */
  "@type": "oa:TextualBody";
  /**
   * An array of multiple values in string representation specific for the particular selector. This value could contain a string representation of a json value.
   */
  "oa:value": string[];
  /**
   * Provides information on how the value was derived. This could be a link to a service that provided the value or a link to the source of the value.
   */
  "dcterms:references"?: string;
  /**
   * A score between 0 and 1 indicating the confidence in the value. 1 is the highest confidence and 0 is the lowest.
   */
  "ods:score"?: number;
}
