/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Assertion {
  /**
   * The identifier for the Assertion object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Assertion
   */
  "@type": "ods:Assertion";
  /**
   * https://rs.tdwg.org/dwc/terms/measurementID
   */
  "dwc:measurementID"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/parentMeasurementID
   */
  "dwc:parentMeasurementID"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/measurementType
   */
  "dwc:measurementType"?: string;
  /**
   * https://rs.tdwg.org/dwc/iri/measurementType
   */
  "dwciri:measurementType"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/measurementDeterminedDate
   */
  "dwc:measurementDeterminedDate"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/measurementValue
   */
  "dwc:measurementValue"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/measurementValue
   */
  "dwciri:measurementValue"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/measurementAccuracy
   */
  "dwc:measurementAccuracy"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/measurementUnit
   */
  "dwc:measurementUnit"?: string;
  /**
   * https://rs.tdwg.org/dwc/iri/measurementUnit
   */
  "dwciri:measurementUnit"?: string;
  /**
   * Name of the agent who made the assertion
   */
  "ods:assertionByAgentName"?: string;
  /**
   * ID of the agent who made the assertion, recommended to be a ORCID or Wikidata identifier
   */
  "ods:assertionByAgentID"?: string;
  /**
   * The protocol used to make the assertion
   */
  "ods:assertionProtocol"?: string;
  /**
   * The ID of the protocol used to make the assertion
   */
  "ods:assertionProtocolID"?: string;
  /**
   * Remarks about the assertion
   */
  "ods:assertionRemarks"?: string;
}
