/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Assertion {
  assertionType: string;
  assertionMadeDate?: string;
  assertionEffectiveDate?: string;
  assertionValue?: string;
  assertionValueNumeric?: number;
  assertionUnit?: string;
  assertionByAgentName?: string;
  assertionByAgentId?: string;
  assertionProtocol?: string;
  assertionProtocolId?: string;
  assertionRemarks?: string;
  [k: string]: unknown;
}
