/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ChronometricAge {
  /**
   * The identifier for the Chronometric Age object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case ods:ChronometricAge
   */
  "@type": "ods:ChronometricAge";
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeID
   */
  "chrono:chronometricAgeID"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/verbatimChronometricAge
   */
  "chrono:verbatimChronometricAge"?: string;
  /**
   * The verbatim name of the protocol used to determine the chronometric age.
   */
  "ods:verbatimChronometricAgeProtocol"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/uncalibratedChronometricAge
   */
  "chrono:uncalibratedChronometricAge"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeConversionProtocol
   */
  "chrono:chronometricAgeConversionProtocol"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/earliestChronometricAge
   */
  "chrono:earliestChronometricAge"?: number;
  /**
   * https://rs.tdwg.org/chrono/terms/earliestChronometricAgeReferenceSystem
   */
  "chrono:earliestChronometricAgeReferenceSystem"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/latestChronometricAge
   */
  "chrono:latestChronometricAge"?: number;
  /**
   * https://rs.tdwg.org/chrono/terms/latestChronometricAgeReferenceSystem
   */
  "chrono:latestChronometricAgeReferenceSystem"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeUncertaintyInYears
   */
  "chrono:chronometricAgeUncertaintyInYears"?: number;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeUncertaintyMethod
   */
  "chrono:chronometricAgeUncertaintyMethod"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/materialDated
   */
  "chrono:materialDated"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/materialDatedID
   */
  "chrono:materialDatedID"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/materialDatedRelationship
   */
  "chrono:materialDatedRelationship"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeDeterminedBy
   */
  "chrono:chronometricAgeDeterminedBy"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeDeterminedDate
   */
  "chrono:chronometricAgeDeterminedDate"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeReferences
   */
  "chrono:chronometricAgeReferences"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeRemarks
   */
  "chrono:chronometricAgeRemarks"?: string;
}
