/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Citation {
  /**
   * https://purl.org/dc/terms/type
   */
  "dcterms:type"?: string;
  /**
   * https://purl.org/dc/terms/date
   */
  "dcterms:date"?: string;
  /**
   * https://purl.org/dc/terms/title
   */
  "dcterms:title"?: string;
  /**
   * https://purl.org/dc/elements/1.1/creator
   */
  "dcterms:creator"?: string;
  /**
   * Unclear yet
   */
  "???:citationPageNumber"?: string;
  /**
   * Unclear yet
   */
  "???:citationRemarks"?: string;
  /**
   * Unclear yet
   */
  "???:referenceType"?: string;
  /**
   * https://dublincore.org/usage/terms/history/#bibliographicCitation-002
   */
  "dcterms:bibliographicCitation"?: string;
  /**
   * Unclear yet
   */
  "???:referenceYear"?: string;
  /**
   * Unclear yet
   */
  "???:referenceIri"?: string;
  /**
   * Unclear yet
   */
  "???:isPeerReviewed"?: boolean;
  [k: string]: unknown;
}
