/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Based on https://rs.gbif.org/extension/gbif/1.0/references.xml but includes ods specific terms
 */
export interface Citation {
  /**
   * The identifier for the Citation object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Citation
   */
  "@type": "ods:Citation";
  /**
   * https://purl.org/dc/terms/identifier
   */
  "dcterms:identifier"?: string;
  /**
   * https://purl.org/dc/terms/type
   */
  "dcterms:type"?: string;
  /**
   * https://purl.org/dc/terms/date
   */
  "dcterms:date"?: string;
  /**
   * https://purl.org/dc/terms/title
   */
  "dcterms:title"?: string;
  /**
   * https://purl.org/dc/elements/1.1/creator
   */
  "dcterms:creator"?: string;
  /**
   * Page number of the citation
   */
  "ods:citationPageNumber"?: string;
  /**
   * Any further remarks about the citation
   */
  "ods:citationRemarks"?: string;
  /**
   * The type of reference
   */
  "ods:referenceType"?: string;
  /**
   * https://dublincore.org/usage/terms/history/#bibliographicCitation-002
   */
  "dcterms:bibliographicCitation"?: string;
  /**
   * The year the reference was published
   */
  "ods:referenceYear"?: number;
  /**
   * Reference to the web source of this citation
   */
  "ods:referenceIRI"?: string;
  /**
   * Is the citation peer reviewed?
   */
  "ods:isPeerReviewed"?: boolean;
}
