/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DigitalSpecimen {
  /**
   * The unique digital identifier of the object
   */
  "ods:id": string;
  /**
   * The version of the object, each change generates a new version
   */
  "ods:version": number;
  /**
   * The timestamp that the object version was created in DiSSCo
   */
  "ods:created": string;
  /**
   * The FDO type of the object
   */
  "ods:type": string;
  /**
   * The MIDS level of the object, see https://www.tdwg.org/community/cd/mids/
   */
  "ods:midsLevel": number;
  /**
   * The physical specimen identifier of the object. When locally unique this is a combination between source-system-id and the local identifier
   */
  "ods:normalisedPhysicalSpecimenId"?: string;
  /**
   * To indicate if the physical identifier is globally unique or locally unique
   */
  "ods:physicalSpecimenIdType": "Resolvable" | "Global" | "Local";
  /**
   * The topic origin of the specimen
   */
  "ods:topicOrigin"?: "Natural" | "Human-made" | "Mixed origin" | "Unclassified";
  /**
   * The topic domain of the specimen
   */
  "ods:topicDomain"?:
    | "Life"
    | "Environment"
    | "Earth System"
    | "Extraterrestrial"
    | "Cultural Artefacts"
    | "Archive Material"
    | "Unclassified";
  /**
   * The topic discipline of the specimen
   */
  "ods:topicDiscipline"?:
    | "Anthropology"
    | "Botany"
    | "Astrogeology"
    | "Geology"
    | "Microbiology"
    | "Palaeontology"
    | "Zoology"
    | "Ecology"
    | "Other Biodiversity"
    | "Other Geodiversity"
    | "Unclassified";
  /**
   * The specimen is marked as a type specimen
   */
  "ods:markedAsType"?: boolean;
  /**
   * Indicates if there are any media objects attached to this specimen
   */
  "ods:hasMedia"?: boolean;
  /**
   * The accepted specimen name of the digital specimen
   */
  "ods:specimenName"?: string;
  /**
   * The handle to the source system object which retrieved the data from the CMS
   */
  "ods:sourceSystem": string;
  /**
   * License for the metadata of the physical specimen
   */
  "ods:livingOrPreserved"?: string;
  /**
   * http://purl.org/dc/terms/license
   */
  "dcterms:license": string;
  /**
   * Modification date for specimen information
   */
  "dcterms:modified"?: string;
  /**
   * The basis for the record
   */
  "dwc:basisOfRecord"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/preparations
   */
  "dwc:preparations"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/disposition
   */
  "dwc:disposition"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/institutionCode
   */
  "dwc:institutionCode"?: string;
  /**
   * ROR or Wikidata identifier, based on https://rs.tdwg.org/dwc/terms/institutionID
   */
  "dwc:institutionId"?: string;
  /**
   * Full museum name according to ROR or Wikidata
   */
  "dwc:institutionName"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/collectionCode
   */
  "dwc:collectionCode"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/collectionID
   */
  "dwc:collectionId"?: string;
  /**
   * ROR or Wikidata identifier for the owning institution
   */
  "dwc:ownerInstitutionId"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/recordedBy
   */
  "dwc:recordedBy"?: string;
  "???:recordedByAgent"?: Agent;
  /**
   * https://rs.tdwg.org/dwc/terms/recordedByID
   */
  "dwc:recordedById"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/datasetName
   */
  "dwc:datasetName"?: string;
  /**
   * https://purl.org/dc/terms/accessRights
   */
  "dcterms:accessRights"?: string;
  /**
   * https://purl.org/dc/terms/rightsHolder
   */
  "dcterms:rightsHolder"?: string;
  materialEntity?: MaterialEntity[];
  "dwc:identification"?: Identification[];
  assertions?: Assertion[];
  occurrences?: Occurrence[];
  entityRelationships?: EntityRelationship[];
  citations?: Citation[];
  identifiers?: Identifier[];
  chronometricAge?: ChronometricAge[];
  [k: string]: unknown;
}
export interface Agent {
  agentRole?: string;
  agentType: string;
  agentName: string;
  agentRoleBegan?: string;
  agentRoleEnded?: string;
  agentRoleOrder?: number;
  identifiers?: Identification[];
  [k: string]: unknown;
}
export interface Identification {
  /**
   * Check DWC terms
   */
  "dwc:identificationID"?: string;
  /**
   * Unclear yet
   */
  "???:identificationType"?: string;
  /**
   * Unclear yet
   */
  "???:taxonFormula"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/verbatimIdentification
   */
  "dwc:verbatimIdentification"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/typeStatus
   */
  "dwc:typeStatus"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/identifiedBy
   */
  "dwc:identifiedBy"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/identifiedByID
   */
  "dwc:identifiedById"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/dateIdentified
   */
  "dwc:dateIdentified"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/identificationReferences
   */
  "dwc:identificationReferences"?: string;
  /**
   * If this is the accepted identification, based on https://rs.tdwg.org/dwc/terms/identificationVerificationStatus
   */
  "dwc:identificationVerificationStatus": boolean;
  /**
   * https://rs.tdwg.org/dwc/terms/identificationRemarks
   */
  "dwc:identificationRemarks"?: string;
  /**
   * Unclear yet
   */
  "???:typeDesignationType"?: string;
  /**
   * Unclear yet
   */
  "???:typeDesignatedBy"?: string;
  citations?: Citation[];
  taxonIdentifications?: {
    /**
     * See DWC Terms
     */
    "dwc:taxonID"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/scientificName
     */
    "dwc:scientificName": string;
    /**
     * https://rs.tdwg.org/dwc/terms/scientificNameAuthorship
     */
    "dwc:scientificNameAuthorship"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/nameAccordingTo
     */
    "dwc:nameAccordingTo"?: string;
    "dwc:namePublishedInYear"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/taxonRank
     */
    "dwc:taxonRank"?: string;
    /**
     * Unclear yet
     */
    "???:taxonSource"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/taxonRemarks
     */
    "dwc:taxonRemarks"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/kingdom
     */
    "dwc:kingdom"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/phylum
     */
    "dwc:phylum"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/class
     */
    "dwc:class"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/order
     */
    "dwc:order"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/family
     */
    "dwc:family"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/subfamily
     */
    "dwc:subfamily"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/genus
     */
    "dwc:genus"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/specificEpithet
     */
    "dwc:specificEpithet"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/taxonomicStatus
     */
    "dwc:taxonomicStatus"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/nomenclaturalCode
     */
    "dwc:nomenclaturalCode"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/vernacularName
     */
    "dwc:vernacularName"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/subgenus
     */
    "dwc:subgenus"?: string;
    /**
     * Unclear yet
     */
    "???:acceptedScientificName"?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface Citation {
  /**
   * https://purl.org/dc/terms/type
   */
  "dcterms:type"?: string;
  /**
   * https://purl.org/dc/terms/date
   */
  "dcterms:date"?: string;
  /**
   * https://purl.org/dc/terms/title
   */
  "dcterms:title"?: string;
  /**
   * https://purl.org/dc/elements/1.1/creator
   */
  "dcterms:creator"?: string;
  /**
   * Unclear yet
   */
  "???:citationPageNumber"?: string;
  /**
   * Unclear yet
   */
  "???:citationRemarks"?: string;
  /**
   * Unclear yet
   */
  "???:referenceType"?: string;
  /**
   * https://dublincore.org/usage/terms/history/#bibliographicCitation-002
   */
  "dcterms:bibliographicCitation"?: string;
  /**
   * Unclear yet
   */
  "???:referenceYear"?: string;
  /**
   * Unclear yet
   */
  "???:referenceIri"?: string;
  /**
   * Unclear yet
   */
  "???:isPeerReviewed"?: boolean;
  [k: string]: unknown;
}
export interface MaterialEntity {
  materialEntityId?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/preparations
   */
  "dwc:preparations"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/disposition
   */
  "dwc:disposition"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/institutionCode
   */
  "dwc:institutionCode"?: string;
  /**
   * ROR or Wikidata identifier, based on https://rs.tdwg.org/dwc/terms/institutionID
   */
  "???:institutionId"?: string;
  /**
   * Full museum name according to ROR or Wikidata
   */
  "dwc:institutionName"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/collectionCode
   */
  "dwc:collectionCode"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/collectionID
   */
  "dwc:collectionId"?: string;
  /**
   * ROR or Wikidata identifier for the owning institution
   */
  "dwc:ownerInstitutionId"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/recordedBy
   */
  "dwc:recordedBy"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/recordedByID
   */
  "dwc:recordedById"?: string;
  identifications?: Identification[];
  assertions?: Assertion[];
  entityRelationships?: EntityRelationship[];
  citations?: Citation[];
  identifiers?: Identification[];
  events?: Event[];
  [k: string]: unknown;
}
export interface Assertion {
  assertionType: string;
  assertionMadeDate?: string;
  assertionEffectiveDate?: string;
  assertionValue?: string;
  assertionValueNumeric?: number;
  assertionUnit?: string;
  assertionByAgentName?: string;
  assertionByAgentId?: string;
  assertionProtocol?: string;
  assertionProtocolId?: string;
  assertionRemarks?: string;
  [k: string]: unknown;
}
export interface EntityRelationship {
  entityRelationshipType: string;
  /**
   * The link to the referenced resource. This could be an internal object linked through the PID or an external object
   */
  objectEntityIri: string;
  /**
   * The data time on which the relationship was established
   */
  entityRelationshipDate: string;
  /**
   * When multiple relationships are added an order can be defined
   */
  entityRelationshipOrder?: number;
  /**
   * The name of the relationship creator
   */
  entityRelationshipCreatorName?: string;
  /**
   * The PID of the creator, this could be a Orcid(user), PID(machine) or ROR(organisation)
   */
  entityRelationshipCreatorId: string;
  [k: string]: unknown;
}
export interface Event {
  "???:eventName"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/fieldNumber
   */
  "dwc:fieldNumber"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/eventDate
   */
  "dwc:eventDate"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/year
   */
  "dwc:year"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/month
   */
  "dwc:month"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/day
   */
  "dwc:day"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/habitat
   */
  "dwc:habitat"?: string;
  "???:protocolDescription"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/sampleSizeValue
   */
  "dwc:sampleSizeValue"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/sampleSizeUnit
   */
  "dwc:sampleSizeUnit"?: string;
  "???:eventEffort"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/fieldNotes
   */
  "dwc:fieldNotes"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/eventRemarks
   */
  "dwc:eventRemarks"?: string;
  "???:collectorName"?: string;
  "???:collectorId"?: string;
  location?: Location;
  [k: string]: unknown;
}
export interface Location {
  /**
   * https://rs.tdwg.org/dwc/terms/continent
   */
  "dwc:continent"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/waterBody
   */
  "dwc:waterBody"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/islandGroup
   */
  "dwc:islandGroup"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/island
   */
  "dwc:island"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/country
   */
  "dwc:country"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/countryCode
   */
  "dwc:countryCode"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/stateProvince
   */
  "dwc:stateProvince"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/county
   */
  "dwc:county"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/municipality
   */
  "dwc:municipality"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/locality
   */
  "dwc:locality"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/minimumElevationInMeters
   */
  "dwc:minimumElevationInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/higherGeography
   */
  "dwc:higherGeography"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/maximumElevationInMeters
   */
  "dwc:maximumElevationInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/minimumDistanceAboveSurfaceInMeters
   */
  "dwc:minimumDistanceAboveSurfaceInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/maximumDistanceAboveSurfaceInMeters
   */
  "dwc:maximumDistanceAboveSurfaceInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/minimumDepthInMeters
   */
  "dwc:minimumDepthInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/maximumDepthInMeters
   */
  "dwc:maximumDepthInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/verticalDatum
   */
  "dwc:verticalDatum"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/locationAccordingTo
   */
  "dwc:locationAccordingTo"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/locationRemarks
   */
  "dwc:locationRemarks"?: string;
  georeference?: {
    /**
     * https://rs.tdwg.org/dwc/terms/decimalLatitude
     */
    "dwc:decimalLatitude"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/decimalLongitude
     */
    "dwc:decimalLongitude"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/geodeticDatum
     */
    "dwc:geodeticDatum"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters
     */
    "dwc:coordinateUncertaintyInMeters"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/coordinatePrecision
     */
    "dwc:coordinatePrecision"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/pointRadiusSpatialFit
     */
    "dwc:pointRadiusSpatialFit"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/footprintWKT
     */
    "dwc:footprintWkt"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/footprintSRS
     */
    "dwc:footprintSrs"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/footprintSpatialFit
     */
    "dwc:footprintSpatialFit"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferencedBy
     */
    "dwc:georeferencedBy"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferencedDate
     */
    "dwc:georeferencedDate"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferenceProtocol
     */
    "dwc:georeferenceProtocol"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferenceSources
     */
    "dwc:georeferenceSources"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferenceRemarks
     */
    "dwc:georeferenceRemarks"?: string;
    "???:preferredSpatialRepresentation"?: string;
    [k: string]: unknown;
  };
  geologicalContext?: {
    /**
     * https://rs.tdwg.org/dwc/terms/earliestEonOrLowestEonothem
     */
    "dwc:earliestEonOrLowestEonothem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestEonOrHighestEonothem
     */
    "dwc:latestEonOrHighestEonothem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestEraOrLowestErathem
     */
    "dwc:earliestEraOrLowestErathem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestEraOrHighestErathem
     */
    "dwc:latestEraOrHighestErathem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestPeriodOrLowestSystem
     */
    "dwc:earliestPeriodOrLowestSystem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestPeriodOrHighestSystem
     */
    "dwc:latestPeriodOrHighestSystem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestEpochOrLowestSeries
     */
    "dwc:earliestEpochOrLowestSeries"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestEpochOrHighestSeries
     */
    "dwc:latestEpochOrHighestSeries"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestAgeOrLowestStage
     */
    "dwc:earliestAgeOrLowestStage"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestAgeOrHighestStage
     */
    "dwc:latestAgeOrHighestStage"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/lowestBiostratigraphicZone
     */
    "dwc:lowestBiostratigraphicZone"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/highestBiostratigraphicZone
     */
    "dwc:highestBiostratigraphicZone"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/lithostratigraphicTerms
     */
    "dwc:lithostratigraphicTerms"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/group
     */
    "dwc:group"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/formation
     */
    "dwc:formation"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/member
     */
    "dwc:member"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/bed
     */
    "dwc:bed"?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Occurrence {
  /**
   * https://rs.tdwg.org/dwc/terms/organismQuantity
   */
  "dwc:organismQuantity"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/organismQuantityType
   */
  "dwc:organismQuantityType"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/sex
   */
  "dwc:sex"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/lifeStage
   */
  "dwc:lifeStage"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/reproductiveCondition
   */
  "dwc:reproductiveCondition"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/behavior
   */
  "dwc:behavior"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/establishmentMeans
   */
  "dwc:establishmentMeans"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/occurrenceStatus
   */
  "dwc:occurrenceStatus"?: "present" | "absent";
  /**
   * https://rs.tdwg.org/dwc/terms/pathway
   */
  "dwc:pathway"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/degreeOfEstablishment
   */
  "dwc:degreeOfEstablishment"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/georeferenceVerificationStatus
   */
  "dwc:georeferenceVerificationStatus"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/occurrenceRemarks
   */
  "dwc:occurrenceRemarks"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/informationWithheld
   */
  "dwc:informationWithheld"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/dataGeneralizations
   */
  "dwc:dataGeneralizations"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/recordedBy
   */
  "dwc:recordedBy"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/recordedByID
   */
  "dwc:recordedById"?: string;
  "???:eventName"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/fieldNumber
   */
  "dwc:fieldNumber"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/eventDate
   */
  "dwc:eventDate"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/year
   */
  "dwc:year"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/month
   */
  "dwc:month"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/day
   */
  "dwc:day"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/habitat
   */
  "dwc:habitat"?: string;
  "???:protocolDescription"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/sampleSizeValue
   */
  "dwc:sampleSizeValue"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/sampleSizeUnit
   */
  "dwc:sampleSizeUnit"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/samplingProtocol
   */
  "dwc:samplingProtocol"?: string;
  "???:eventEffort"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/fieldNotes
   */
  "dwc:fieldNotes"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/eventRemarks
   */
  "dwc:eventRemarks"?: string;
  "???:collectorName"?: string;
  "???:collectorId"?: string;
  assertions?: Assertion[];
  location?: Location;
  [k: string]: unknown;
}
export interface Identifier {
  /**
   * The type of the identifier
   */
  "???:identifierType"?: string;
  /**
   * The value for the identifier
   */
  "???:identifierValue": string;
  /**
   * Is the identifier part of the physical label
   */
  "???:partOfLabel"?: boolean;
  /**
   * Part of barcode or nfc chip
   */
  "???:barcodeOrNfc"?: string;
  isIdPersistent?: boolean;
  [k: string]: unknown;
}
export interface ChronometricAge {
  /**
   * https://rs.tdwg.org/chrono/terms/verbatimChronometricAge
   */
  "chrono:verbatimChronometricAge"?: string;
  "???:verbatimChronometricAgeProtocol"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/uncalibratedChronometricAge
   */
  "chrono:uncalibratedChronometricAge"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeConversionProtocol
   */
  "chrono:chronometricAgeConversionProtocol"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/earliestChronometricAge
   */
  "chrono:earliestChronometricAge"?: number;
  /**
   * https://rs.tdwg.org/chrono/terms/earliestChronometricAgeReferenceSystem
   */
  "chrono:earliestChronometricAgeReferenceSystem"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/latestChronometricAge
   */
  "chrono:latestChronometricAge"?: number;
  /**
   * https://rs.tdwg.org/chrono/terms/latestChronometricAgeReferenceSystem
   */
  "chrono:latestChronometricAgeReferenceSystem"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeUncertaintyInYears
   */
  "chrono:chronometricAgeUncertaintyInYears"?: number;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeUncertaintyMethod
   */
  "chrono:chronometricAgeUncertaintyMethod"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/materialDated
   */
  "chrono:materialDated"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/materialDatedID
   */
  "chrono:materialDatedId"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/materialDatedRelationship
   */
  "chrono:materialDatedRelationship"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeDeterminedBy
   */
  "chrono:chronometricAgeDeterminedBy"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeDeterminedDate
   */
  "chrono:chronometricAgeDeterminedDate"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeReferences
   */
  "chrono:chronometricAgeReferences"?: string;
  /**
   * https://rs.tdwg.org/chrono/terms/chronometricAgeRemarks
   */
  "chrono:chronometricAgeRemarks"?: string;
  [k: string]: unknown;
}
