/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DigitalEntity {
  /**
   * The unique digital identifier of the object
   */
  "ods:id": string;
  /**
   * The version of the object, each change generates a new version
   */
  "ods:version": number;
  /**
   * The timestamp that the object version was created in DiSSCo
   */
  "ods:created": string;
  /**
   * https://purl.org/dc/terms/type, which matches the FDO type of the object
   */
  "dcterms:type"?:
    | "Collection"
    | "Dataset"
    | "Event"
    | "Image"
    | "InteractiveResource"
    | "MovingImage"
    | "PhysicalObject"
    | "Service"
    | "Software"
    | "Sound"
    | "StillImage"
    | "Text";
  /**
   * https://rs.tdwg.org/ac/terms/accessURI
   */
  "ac:accessUri": string;
  /**
   * ROR or Wikidata identifier, based on https://rs.tdwg.org/dwc/terms/institutionID
   */
  "dwc:institutionId"?: string;
  /**
   * Full museum name according to ROR or Wikidata
   */
  "dwc:institutionName"?: string;
  /**
   * https://ns.adobe.com/xap/1.0/rights/WebStatement
   */
  "xmpRights:webStatement"?: string;
  /**
   * https://purl.org/dc/terms/format
   */
  "dcterms:format"?: string;
  /**
   * https://purl.org/dc/terms/license
   */
  "dcterms:license": string;
  /**
   * https://purl.org/dc/terms/description
   */
  "dcterms:description"?: string;
  /**
   * https://purl.org/dc/terms/rights
   */
  "dcterms:rights"?: string;
  "???:rightsUri"?: string;
  /**
   * https://purl.org/dc/terms/accessRights
   */
  "dcterms:accessRights"?: string;
  /**
   * https://purl.org/dc/terms/rightsHolder
   */
  "dcterms:rightsHolder"?: string;
  /**
   * https://purl.org/dc/terms/source
   */
  "dcterms:source"?: string;
  "???:sourceUri"?: string;
  /**
   * https://purl.org/dc/elements/1.1/creator
   */
  "dcterms:creator"?: string;
  /**
   * https://purl.org/dc/terms/created
   */
  "dcterms:created"?: string;
  /**
   * https://purl.org/dc/terms/modified
   */
  "dcterms:modified"?: string;
  assertions?: Assertion[];
  citations?: Citation[];
  identifiers?: Identifier[];
  entityRelationships?: EntityRelationship[];
  [k: string]: unknown;
}
export interface Assertion {
  assertionType: string;
  assertionMadeDate?: string;
  assertionEffectiveDate?: string;
  assertionValue?: string;
  assertionValueNumeric?: number;
  assertionUnit?: string;
  assertionByAgentName?: string;
  assertionByAgentId?: string;
  assertionProtocol?: string;
  assertionProtocolId?: string;
  assertionRemarks?: string;
  [k: string]: unknown;
}
export interface Citation {
  /**
   * https://purl.org/dc/terms/type
   */
  "dcterms:type"?: string;
  /**
   * https://purl.org/dc/terms/date
   */
  "dcterms:date"?: string;
  /**
   * https://purl.org/dc/terms/title
   */
  "dcterms:title"?: string;
  /**
   * https://purl.org/dc/elements/1.1/creator
   */
  "dcterms:creator"?: string;
  /**
   * Unclear yet
   */
  "???:citationPageNumber"?: string;
  /**
   * Unclear yet
   */
  "???:citationRemarks"?: string;
  /**
   * Unclear yet
   */
  "???:referenceType"?: string;
  /**
   * https://dublincore.org/usage/terms/history/#bibliographicCitation-002
   */
  "dcterms:bibliographicCitation"?: string;
  /**
   * Unclear yet
   */
  "???:referenceYear"?: string;
  /**
   * Unclear yet
   */
  "???:referenceIri"?: string;
  /**
   * Unclear yet
   */
  "???:isPeerReviewed"?: boolean;
  [k: string]: unknown;
}
export interface Identifier {
  /**
   * The type of the identifier
   */
  "???:identifierType"?: string;
  /**
   * The value for the identifier
   */
  "???:identifierValue": string;
  /**
   * Is the identifier part of the physical label
   */
  "???:partOfLabel"?: boolean;
  /**
   * Part of barcode or nfc chip
   */
  "???:barcodeOrNfc"?: string;
  isIdPersistent?: boolean;
  [k: string]: unknown;
}
export interface EntityRelationship {
  entityRelationshipType: string;
  /**
   * The link to the referenced resource. This could be an internal object linked through the PID or an external object
   */
  objectEntityIri: string;
  /**
   * The data time on which the relationship was established
   */
  entityRelationshipDate: string;
  /**
   * When multiple relationships are added an order can be defined
   */
  entityRelationshipOrder?: number;
  /**
   * The name of the relationship creator
   */
  entityRelationshipCreatorName?: string;
  /**
   * The PID of the creator, this could be a Orcid(user), PID(machine) or ROR(organisation)
   */
  entityRelationshipCreatorId: string;
  [k: string]: unknown;
}
