/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Based on https://rs.gbif.org/extension/resource_relationship_2024-02-19.xml but with ods specific terms
 */
export interface EntityRelationship {
  /**
   * The identifier for Entity Relationship digital object.
   */
  "@id"?: string;
  /**
   * The type of the record, in this case a ods:EntityRelationship
   */
  "@type": "ods:EntityRelationship";
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipOfResource
   */
  "dwc:relationshipOfResource": string;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipOfResourceID
   */
  "dwc:relationshipOfResourceID"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/relatedResourceID
   */
  "dwc:relatedResourceID": string;
  /**
   * The URI of the related resource
   */
  "ods:relatedResourceURI"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipEstablishedDate
   */
  "dwc:relationshipEstablishedDate"?: string;
  /**
   * When multiple relationships are added an order can be defined
   */
  "ods:entityRelationshipOrder"?: number;
  "ods:RelationshipAccordingToAgent"?: Agent;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipAccordingTo
   */
  "dwc:relationshipAccordingTo"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipRemarks
   */
  "dwc:relationshipRemarks"?: string;
}
/**
 * The agent who created the entity relationship. Contains an ods:Agent object
 */
export interface Agent {
  /**
   * The identifier for the Agent object
   */
  "@id"?: string;
  /**
   * The type of the agent, the prov ontology is only used in the prov-o createUpdateTombstoneEvent
   */
  "@type": "schema:Person" | "schema:Organisation" | "as:Application" | "prov:Person" | "prov:SoftwareAgent";
  /**
   * Full name of the agent
   */
  "schema:name"?: string;
  /**
   * Indicates the role of the agent, https://schema.org/roleName
   */
  "schema:roleName"?: string;
  /**
   * Date the agent began the role
   */
  "schema:startDate"?: string;
  /**
   * Date the agent ended the role
   */
  "schema:endDate"?: string;
  /**
   * Order of the agent in the role. Can be used to indicate the order of importance
   */
  "ods:roleOrder"?: number;
  /**
   * Email of the agent, can be present in case the agent is a maintainer of a MAS
   */
  "schema:email"?: string;
  /**
   * URL of the agent, can be present in case the agent is a maintainer of a MAS
   */
  "schema:url"?: string;
  /**
   * Contains zero or more ods:Identifier objects
   */
  "ods:hasIdentifier"?: Identifier[];
}
/**
 * Based on https://rs.gbif.org/extension/gbif/1.0/identifier.xml but includes ods specific terms
 */
export interface Identifier {
  /**
   * The identifier for the Identifier object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Identifier
   */
  "@type": "ods:Identifier";
  /**
   * The type of the identifier, https://purl.org/dc/elements/1.1/title
   */
  "dcterms:title": string;
  /**
   * The local title of the identifier
   */
  "ods:localTitle"?: string;
  /**
   * The value for the identifier, https://purl.org/dc/terms/identifier
   */
  "dcterms:identifier": string;
  /**
   * Mime type of content returned by identifier in case the identifier is resolvable. https://purl.org/dc/terms/format
   */
  "dcterms:format"?: string;
  /**
   * Keywords qualifying the identifier https://purl.org/dc/terms/subject
   */
  "dcterms:subject"?: string;
  /**
   * Indicates whether the identifier is part of the physical label
   */
  "ods:isPartOfLabel"?: boolean;
  /**
   * Indicates whether the identifier is part of the barcode or nfc chip
   */
  "ods:isBarcodeOrNFC"?: boolean;
  /**
   * Indicates whether the identifier is a persistent identifier
   */
  "ods:isIDPersistent"?: boolean;
}
