/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Based on https://rs.gbif.org/extension/resource_relationship_2024-02-19.xml but with ods specific terms
 */
export interface EntityRelationship {
  /**
   * The identifier for Entity Relationship digital object.
   */
  "@id"?: string;
  /**
   * The type of the record, in this case a ods:EntityRelationship
   */
  "@type": "ods:EntityRelationship";
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipOfResource
   */
  "dwc:relationshipOfResource": string;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipOfResourceID
   */
  "dwc:relationshipOfResourceID"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/relatedResourceID
   */
  "dwc:relatedResourceID": string;
  /**
   * The URI of the related resource
   */
  "ods:relatedResourceURI"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipEstablishedDate
   */
  "dwc:relationshipEstablishedDate"?: string;
  /**
   * When multiple relationships are added an order can be defined
   */
  "ods:entityRelationshipOrder"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipAccordingTo
   */
  "dwc:relationshipAccordingTo"?: string;
  /**
   * The PID of the creator, this could be a Orcid(user), PID(machine) or ROR(organisation)
   */
  "ods:relationshipAccordingToID"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/relationshipRemarks
   */
  "dwc:relationshipRemarks"?: string;
}
