/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Event {
  "???:eventName"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/fieldNumber
   */
  "dwc:fieldNumber"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/eventDate
   */
  "dwc:eventDate"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/year
   */
  "dwc:year"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/month
   */
  "dwc:month"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/day
   */
  "dwc:day"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/habitat
   */
  "dwc:habitat"?: string;
  "???:protocolDescription"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/sampleSizeValue
   */
  "dwc:sampleSizeValue"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/sampleSizeUnit
   */
  "dwc:sampleSizeUnit"?: string;
  "???:eventEffort"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/fieldNotes
   */
  "dwc:fieldNotes"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/eventRemarks
   */
  "dwc:eventRemarks"?: string;
  "???:collectorName"?: string;
  "???:collectorId"?: string;
  location?: Location;
  [k: string]: unknown;
}
export interface Location {
  /**
   * https://rs.tdwg.org/dwc/terms/continent
   */
  "dwc:continent"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/waterBody
   */
  "dwc:waterBody"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/islandGroup
   */
  "dwc:islandGroup"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/island
   */
  "dwc:island"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/country
   */
  "dwc:country"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/countryCode
   */
  "dwc:countryCode"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/stateProvince
   */
  "dwc:stateProvince"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/county
   */
  "dwc:county"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/municipality
   */
  "dwc:municipality"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/locality
   */
  "dwc:locality"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/minimumElevationInMeters
   */
  "dwc:minimumElevationInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/higherGeography
   */
  "dwc:higherGeography"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/maximumElevationInMeters
   */
  "dwc:maximumElevationInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/minimumDistanceAboveSurfaceInMeters
   */
  "dwc:minimumDistanceAboveSurfaceInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/maximumDistanceAboveSurfaceInMeters
   */
  "dwc:maximumDistanceAboveSurfaceInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/minimumDepthInMeters
   */
  "dwc:minimumDepthInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/maximumDepthInMeters
   */
  "dwc:maximumDepthInMeters"?: number;
  /**
   * https://rs.tdwg.org/dwc/terms/verticalDatum
   */
  "dwc:verticalDatum"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/locationAccordingTo
   */
  "dwc:locationAccordingTo"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/locationRemarks
   */
  "dwc:locationRemarks"?: string;
  georeference?: {
    /**
     * https://rs.tdwg.org/dwc/terms/decimalLatitude
     */
    "dwc:decimalLatitude"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/decimalLongitude
     */
    "dwc:decimalLongitude"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/geodeticDatum
     */
    "dwc:geodeticDatum"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters
     */
    "dwc:coordinateUncertaintyInMeters"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/coordinatePrecision
     */
    "dwc:coordinatePrecision"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/pointRadiusSpatialFit
     */
    "dwc:pointRadiusSpatialFit"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/footprintWKT
     */
    "dwc:footprintWkt"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/footprintSRS
     */
    "dwc:footprintSrs"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/footprintSpatialFit
     */
    "dwc:footprintSpatialFit"?: number;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferencedBy
     */
    "dwc:georeferencedBy"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferencedDate
     */
    "dwc:georeferencedDate"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferenceProtocol
     */
    "dwc:georeferenceProtocol"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferenceSources
     */
    "dwc:georeferenceSources"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/georeferenceRemarks
     */
    "dwc:georeferenceRemarks"?: string;
    "???:preferredSpatialRepresentation"?: string;
    [k: string]: unknown;
  };
  geologicalContext?: {
    /**
     * https://rs.tdwg.org/dwc/terms/earliestEonOrLowestEonothem
     */
    "dwc:earliestEonOrLowestEonothem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestEonOrHighestEonothem
     */
    "dwc:latestEonOrHighestEonothem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestEraOrLowestErathem
     */
    "dwc:earliestEraOrLowestErathem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestEraOrHighestErathem
     */
    "dwc:latestEraOrHighestErathem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestPeriodOrLowestSystem
     */
    "dwc:earliestPeriodOrLowestSystem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestPeriodOrHighestSystem
     */
    "dwc:latestPeriodOrHighestSystem"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestEpochOrLowestSeries
     */
    "dwc:earliestEpochOrLowestSeries"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestEpochOrHighestSeries
     */
    "dwc:latestEpochOrHighestSeries"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/earliestAgeOrLowestStage
     */
    "dwc:earliestAgeOrLowestStage"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/latestAgeOrHighestStage
     */
    "dwc:latestAgeOrHighestStage"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/lowestBiostratigraphicZone
     */
    "dwc:lowestBiostratigraphicZone"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/highestBiostratigraphicZone
     */
    "dwc:highestBiostratigraphicZone"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/lithostratigraphicTerms
     */
    "dwc:lithostratigraphicTerms"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/group
     */
    "dwc:group"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/formation
     */
    "dwc:formation"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/member
     */
    "dwc:member"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/bed
     */
    "dwc:bed"?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
