/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeologicalContext {
  /**
   * The identifier for the Geological Context object.
   */
  "@id"?: string;
  /**
   * The type of the object, in this case ods:GeologicalContext
   */
  "@type": "ods:GeologicalContext";
  /**
   * The full name of the earliest possible geochronologic eon or lowest chrono-stratigraphic eonothem or the informal name ("Precambrian") attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:earliestEonOrLowestEonothem"?: string;
  /**
   * The full name of the latest possible geochronologic eon or highest chrono-stratigraphic eonothem or the informal name ("Precambrian") attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:latestEonOrHighestEonothem"?: string;
  /**
   * The full name of the earliest possible geochronologic era or lowest chronostratigraphic erathem attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:earliestEraOrLowestErathem"?: string;
  /**
   * The full name of the latest possible geochronologic era or highest chronostratigraphic erathem attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:latestEraOrHighestErathem"?: string;
  /**
   * The full name of the earliest possible geochronologic period or lowest chronostratigraphic system attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:earliestPeriodOrLowestSystem"?: string;
  /**
   * The full name of the latest possible geochronologic period or highest chronostratigraphic system attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:latestPeriodOrHighestSystem"?: string;
  /**
   * The full name of the earliest possible geochronologic epoch or lowest chronostratigraphic series attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:earliestEpochOrLowestSeries"?: string;
  /**
   * The full name of the latest possible geochronologic epoch or highest chronostratigraphic series attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:latestEpochOrHighestSeries"?: string;
  /**
   * The full name of the earliest possible geochronologic age or lowest chronostratigraphic stage attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:earliestAgeOrLowestStage"?: string;
  /**
   * The full name of the latest possible geochronologic age or highest chronostratigraphic stage attributable to the stratigraphic horizon from which the specimen was collected
   */
  "dwc:latestAgeOrHighestStage"?: string;
  /**
   * The full name of the lowest possible geological biostratigraphic zone of the stratigraphic horizon from which the specimen was collected
   */
  "dwc:lowestBiostratigraphicZone"?: string;
  /**
   * The full name of the highest possible geological biostratigraphic zone of the stratigraphic horizon from which the specimen was collected
   */
  "dwc:highestBiostratigraphicZone"?: string;
  /**
   * The combination of all litho-stratigraphic names for the rock from which the specimen was collected
   */
  "dwc:lithostratigraphicTerms"?: string;
  /**
   * The full name of the lithostratigraphic group from which the specimen was collected
   */
  "dwc:group"?: string;
  /**
   * The full name of the lithostratigraphic formation from which the specimen was collected
   */
  "dwc:formation"?: string;
  /**
   * The full name of the lithostratigraphic member from which the specimen was collected
   */
  "dwc:member"?: string;
  /**
   * The full name of the lithostratigraphic bed from which the specimen was collected
   */
  "dwc:bed"?: string;
}
