/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Identification {
  /**
   * The identifier for the Identification object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Identification
   */
  "@type": "ods:Identification";
  /**
   * https://rs.tdwg.org/dwc/terms/identificationID
   */
  "dwc:identificationID"?: string;
  /**
   * The type of identification
   */
  "ods:identificationType"?: string;
  /**
   * The full formula of the taxonomic identification
   */
  "ods:taxonFormula"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/verbatimIdentification
   */
  "dwc:verbatimIdentification"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/typeStatus
   */
  "dwc:typeStatus"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/identifiedBy
   */
  "dwc:identifiedBy"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/identifiedByID
   */
  "dwc:identifiedByID"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/dateIdentified
   */
  "dwc:dateIdentified"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/identificationReferences
   */
  "dwc:identificationReferences"?: string;
  /**
   * If this is the accepted identification, based on https://rs.tdwg.org/dwc/terms/identificationVerificationStatus
   */
  "ods:isVerifiedIdentification": boolean;
  /**
   * https://rs.tdwg.org/dwc/terms/identificationRemarks
   */
  "dwc:identificationRemarks"?: string;
  /**
   * https://rs.tdwg.org/dwc/terms/identificationQualifier
   */
  "dwc:identificationQualifier"?: string;
  /**
   * Can contain zero to more ods:Citation objects
   */
  "ods:hasCitation"?: Citation[];
  /**
   * Can contain zero to more ods:TaxonIdentification objects
   */
  "ods:hasTaxonIdentification"?: {
    /**
     * The identifier for the Taxon Identification object.
     */
    "@id"?: string;
    /**
     * The type of the digital object, in this case a ods:TaxonIdentification
     */
    "@type": "ods:TaxonIdentification";
    /**
     * https://rs.tdwg.org/dwc/terms/taxonID
     */
    "dwc:taxonID"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/scientificName
     */
    "dwc:scientificName": string;
    /**
     * https://rs.tdwg.org/dwc/terms/scientificNameID
     */
    "dwc:scientificNameID"?: string;
    /**
     * A Hyper Text Markup Language (HTML) representation of the scientific name. Includes correct formatting of the name.
     */
    "ods:scientificNameHtmlLabel"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/scientificNameAuthorship
     */
    "dwc:scientificNameAuthorship"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/nameAccordingTo
     */
    "dwc:nameAccordingTo"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/namePublishedInYear
     */
    "dwc:namePublishedInYear"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/taxonRank
     */
    "dwc:taxonRank"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/verbatimTaxonRank
     */
    "dwc:verbatimTaxonRank"?: string;
    /**
     * The source of the taxonomic concept
     */
    "ods:taxonSource"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/taxonRemarks
     */
    "dwc:taxonRemarks"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/kingdom
     */
    "dwc:kingdom"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/phylum
     */
    "dwc:phylum"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/class
     */
    "dwc:class"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/order
     */
    "dwc:order"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/family
     */
    "dwc:family"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/subfamily
     */
    "dwc:subfamily"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/genus
     */
    "dwc:genus"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/specificEpithet
     */
    "dwc:specificEpithet"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/taxonomicStatus
     */
    "dwc:taxonomicStatus"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/nomenclaturalCode
     */
    "dwc:nomenclaturalCode"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/vernacularName
     */
    "dwc:vernacularName"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/subgenus
     */
    "dwc:subgenus"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/acceptedNameUsage
     */
    "dwc:acceptedNameUsage"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/acceptedNameUsageID
     */
    "dwc:acceptedNameUsageID"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/cultivarEpithet
     */
    "dwc:cultivarEpithet"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/genericName
     */
    "dwc:genericName"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/infragenericEpithet
     */
    "dwc:infragenericEpithet"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/infraspecificEpithet
     */
    "dwc:infraspecificEpithet"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/nomenclaturalStatus
     */
    "dwc:nomenclaturalStatus"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/originalNameUsage
     */
    "dwc:originalNameUsage"?: string;
    /**
     * http://rs.tdwg.org/dwc/terms/subtribe
     */
    "dwc:subtribe"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/superfamily
     */
    "dwc:superfamily"?: string;
    /**
     * https://rs.tdwg.org/dwc/terms/tribe
     */
    "dwc:tribe"?: string;
  }[];
}
/**
 * Based on https://rs.gbif.org/extension/gbif/1.0/references.xml but includes ods specific terms
 */
export interface Citation {
  /**
   * The identifier for the Citation object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Citation
   */
  "@type": "ods:Citation";
  /**
   * https://purl.org/dc/terms/identifier
   */
  "dcterms:identifier"?: string;
  /**
   * https://purl.org/dc/terms/type
   */
  "dcterms:type"?: string;
  /**
   * https://purl.org/dc/terms/date
   */
  "dcterms:date"?: string;
  /**
   * https://purl.org/dc/terms/title
   */
  "dcterms:title"?: string;
  "dcterms:creator"?: Agent;
  /**
   * Page number of the citation
   */
  "ods:citationPageNumber"?: string;
  /**
   * Any further remarks about the citation
   */
  "ods:citationRemarks"?: string;
  /**
   * The type of reference
   */
  "ods:referenceType"?: string;
  /**
   * https://dublincore.org/usage/terms/history/#bibliographicCitation-002
   */
  "dcterms:bibliographicCitation"?: string;
  /**
   * The year the reference was published
   */
  "ods:referenceYear"?: number;
  /**
   * Reference to the web source of this citation
   */
  "ods:referenceIRI"?: string;
  /**
   * Is the citation peer reviewed?
   */
  "ods:isPeerReviewed"?: boolean;
}
/**
 * Contains an ods:Agent object
 */
export interface Agent {
  /**
   * The identifier for the Agent object
   */
  "@id"?: string;
  /**
   * The type of the agent, the prov ontology is only used in the prov-o createUpdateTombstoneEvent
   */
  "@type": "schema:Person" | "schema:Organisation" | "as:Application" | "prov:Person" | "prov:SoftwareAgent";
  /**
   * Full name of the agent
   */
  "schema:name"?: string;
  /**
   * Indicates the role of the agent, https://schema.org/roleName
   */
  "schema:roleName"?: string;
  /**
   * Date the agent began the role
   */
  "schema:startDate"?: string;
  /**
   * Date the agent ended the role
   */
  "schema:endDate"?: string;
  /**
   * Order of the agent in the role. Can be used to indicate the order of importance
   */
  "ods:roleOrder"?: number;
  /**
   * Email of the agent, can be present in case the agent is a maintainer of a MAS
   */
  "schema:email"?: string;
  /**
   * URL of the agent, can be present in case the agent is a maintainer of a MAS
   */
  "schema:url"?: string;
  /**
   * Contains zero or more ods:Identifier objects
   */
  "ods:hasIdentifier"?: Identifier[];
}
/**
 * Based on https://rs.gbif.org/extension/gbif/1.0/identifier.xml but includes ods specific terms
 */
export interface Identifier {
  /**
   * The identifier for the Identifier object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:Identifier
   */
  "@type": "ods:Identifier";
  /**
   * The type of the identifier, https://purl.org/dc/elements/1.1/title
   */
  "dcterms:title": string;
  /**
   * The local title of the identifier
   */
  "ods:localTitle"?: string;
  /**
   * The value for the identifier, https://purl.org/dc/terms/identifier
   */
  "dcterms:identifier": string;
  /**
   * Mime type of content returned by identifier in case the identifier is resolvable. https://purl.org/dc/terms/format
   */
  "dcterms:format"?: string;
  /**
   * Keywords qualifying the identifier https://purl.org/dc/terms/subject
   */
  "dcterms:subject"?: string;
  /**
   * Indicates whether the identifier is part of the physical label
   */
  "ods:isPartOfLabel"?: boolean;
  /**
   * Indicates whether the identifier is part of the barcode or nfc chip
   */
  "ods:isBarcodeOrNFC"?: boolean;
  /**
   * Indicates whether the identifier is a persistent identifier
   */
  "ods:isIDPersistent"?: boolean;
}
