/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Identifier {
  /**
   * The type of the identifier
   */
  "???:identifierType"?: string;
  /**
   * The value for the identifier
   */
  "???:identifierValue": string;
  /**
   * Is the identifier part of the physical label
   */
  "???:partOfLabel"?: boolean;
  /**
   * Part of barcode or nfc chip
   */
  "???:barcodeOrNfc"?: string;
  isIdPersistent?: boolean;
  [k: string]: unknown;
}
