/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Secret Variable that need to be supplied to an Digital Object
 */
export interface SecretVariable {
  /**
   * The name of an environmental variable stored remotely
   */
  "schema:name": string;
  /**
   * The name of the key stored in the secret store. NOT the secret's value.
   */
  "ods:secretKeyRef": string;
}
