/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TaxonIdentification {
  /**
   * The identifier for the Taxon Identification object.
   */
  "@id"?: string;
  /**
   * The type of the digital object, in this case a ods:TaxonIdentification
   */
  "@type": "ods:TaxonIdentification";
  /**
   * An identifier for the set of dwc:Taxon information. May be a global unique identifier or an identifier specific to the data set
   */
  "dwc:taxonID"?: string;
  /**
   * The full scientific name, with authorship and date information if known. This should be the name in lowest level taxonomic rank that can be determined. This term should not contain identification qualifications, which should instead be supplied in the dwc:identificationQualifier term
   */
  "dwc:scientificName": string;
  /**
   * An identifier for the nomenclatural (not taxonomic) details of a scientific name
   */
  "dwc:scientificNameID"?: string;
  /**
   * A Hyper Text Markup Language (HTML) representation of the scientific name. Includes correct formatting of the name.
   */
  "ods:scientificNameHTMLLabel"?: string;
  /**
   * The authorship information for the dwc:scientificName formatted according to the conventions of the applicable dwc:nomenclaturalCode
   */
  "dwc:scientificNameAuthorship"?: string;
  /**
   * The four-digit year in which the dwc:scientificName was published
   */
  "dwc:namePublishedInYear"?: string;
  /**
   * The taxonomic rank of the most specific name in the dwc:scientificName
   */
  "dwc:taxonRank"?: string;
  /**
   * The taxonomic rank of the most specific name in the dwc:scientificName as it appears in the original record
   */
  "dwc:verbatimTaxonRank"?: string;
  /**
   * Comments or notes about the taxon or name
   */
  "dwc:taxonRemarks"?: string;
  /**
   * The full scientific name of the kingdom in which the ods:TaxonIdentification is classified
   */
  "dwc:kingdom"?: string;
  /**
   * The full scientific name of the phylum or division in which the ods:TaxonIdentification is classified
   */
  "dwc:phylum"?: string;
  /**
   * The full scientific name of the class in which the ods:TaxonIdentification is classified
   */
  "dwc:class"?: string;
  /**
   * The full scientific name of the order in which the ods:TaxonIdentification is classified
   */
  "dwc:order"?: string;
  /**
   * The full scientific name of the family in which the ods:TaxonIdentification is classified
   */
  "dwc:family"?: string;
  /**
   * The full scientific name of the subfamily in which the ods:TaxonIdentification is classified
   */
  "dwc:subfamily"?: string;
  /**
   * The full scientific name of the genus in which the ods:TaxonIdentification is classified
   */
  "dwc:genus"?: string;
  /**
   * The name of the first or species epithet of the dwc:scientificName
   */
  "dwc:specificEpithet"?: string;
  /**
   * The status of the use of the dwc:scientificName as a label for a taxon. Requires taxonomic opinion to define the scope of a ods:TaxonIdentification. Rules of priority then are used to define the taxonomic status of the nomenclature contained in that scope, combined with the experts opinion. It must be linked to a specific taxonomic reference that defines the concept
   */
  "dwc:taxonomicStatus"?: string;
  /**
   * The nomenclatural code (or codes in the case of an ambiregnal name) under which the dwc:scientificName is constructed
   */
  "dwc:nomenclaturalCode"?: string;
  /**
   * A common or vernacular name
   */
  "dwc:vernacularName"?: string;
  /**
   * The full scientific name of the subgenus in which the ods:TaxonIdentification is classified. Values should include the genus to avoid homonym confusion
   */
  "dwc:subgenus"?: string;
  /**
   * The full name, with authorship and date information if known, of the currently valid (zoological) or accepted (botanical) ods:TaxonIdentification
   */
  "dwc:acceptedNameUsage"?: string;
  /**
   * An identifier for the name usage (documented meaning of the name according to a source) of the currently valid (zoological) or accepted (botanical) taxon
   */
  "dwc:acceptedNameUsageID"?: string;
  /**
   * Part of the name of a cultivar, cultivar group or grex that follows the dwc:scientificName
   */
  "dwc:cultivarEpithet"?: string;
  /**
   * The genus part of the dwc:scientificName without authorship
   */
  "dwc:genericName"?: string;
  /**
   * The infrageneric part of a binomial name at ranks above species but below genus
   */
  "dwc:infragenericEpithet"?: string;
  /**
   * The name of the lowest or terminal infraspecific epithet of the dwc:scientificName, excluding any rank designation
   */
  "dwc:infraspecificEpithet"?: string;
  /**
   * The status related to the original publication of the name and its conformance to the relevant rules of nomenclature. It is based essentially on an algorithm according to the business rules of the code. It requires no taxonomic opinion
   */
  "dwc:nomenclaturalStatus"?: string;
  /**
   * The taxon name, with authorship and date information if known, as it originally appeared when first established under the rules of the associated dwc:nomenclaturalCode. The basionym (botany) or basonym (bacteriology) of the dwc:scientificName or the senior/earlier homonym for replaced names
   */
  "dwc:originalNameUsage"?: string;
  /**
   * The full scientific name of the subtribe in which the ods:TaxonIdentification is classified
   */
  "dwc:subtribe"?: string;
  /**
   * The full scientific name of the superfamily in which the ods:TaxonIdentification is classified
   */
  "dwc:superfamily"?: string;
  /**
   * The full scientific name of the tribe in which the ods:TaxonIdentification is classified
   */
  "dwc:tribe"?: string;
}
